### PR TITLE
JHP-87: Switch to PVC for XNAT data mounts in Kubernetes

### PR DESCRIPTION
**Pull request by andylassiter**

### CODE REVIEW

**Comment by andylassiter** [comment]
Forgot to mention the path translation settings:

Screenshot 2024-07-26 at 11 39 28 AM

**Comment by fxusyd** [comment]
@andylassiter I tried setting the path translation in the plugin as attached screenshot, but can't retrieved it during the pre-spawning. Below is the output user_options generated by pre_spawn_hook.py. Essentially, we only need the part of the src because sub-path is relative. 
```
[INFO 2024-08-13 03:21:47,178 xnat-jupyterhub pre_spawn_hook:20] User options for user xufang server  retrieved from XNAT.
{   'eventTrackingId': '20240813T032140617Z',
    'itemId': 'XNAT01_S00038',
    'projectId': 'P1',
    'servername': '',
    'task_template': {   'container_spec': {   'command': None,
                                               'env': {   'JUPYTERHUB_ROOT_DIR': '/workspace/xufang',
                                                          'XDG_CONFIG_HOME': '/workspace/xufang',
                                                          'XNAT_DATA': '/data',
                                                          'XNAT_HOST': 'https://dev.xnat.ais.sydney.edu.au',
                                                          'XNAT_ITEM_ID': 'XNAT01_S00038',
                                                          'XNAT_PASS': 'xxxxxxx',
                                                          'XNAT_USER': 'xxxxxxx',
                                                          'XNAT_XSI_TYPE': 'xnat:subjectData'},
                                               'image': 'xnat/datascience-notebook:latest',
                                               'labels': {},
                                               'mounts': [   {   'read_only': False,
                                                                 'source': '/data/xnat/workspaces/users/xufang',
                                                                 'target': '/workspace/xufang',
                                                                 'type': 'bind'},
                                                             {   'read_only': True,
                                                                 'source': '/testing/location/archive/P1/arc001/PatientId/',
                                                                 'target': '/data/projects/P1/experiments/PatientId',
                                                                 'type': 'bind'}]},
                         'placement': {'constraints': []},
                         'resources': {   'cpu_limit': 1.0,
                                          'cpu_reservation': 1.0,
                                          'generic_resources': {},
                                          'mem_limit': '2G',
                                          'mem_reservation': '1G'}},
    'userId': 39,
    'xsiType': 'xnat:subjectData'}


```
Screen Shot 2024-08-13 at 1 30 39 pm

**Comment by andylassiter** [comment]
@fxusyd Did you try setting Path Translation Docker Archive Prefix to `.`? That should translate to a relative sub-path.

```
{
  "userId": 1,
  "servername": "20240816T171702861Z",
  "xsiType": "xnat:projectData",
  "itemId": "MyProject",
  "projectId": "MyProject",
  "eventTrackingId": "20240816T171702861Z",
  "task_template": {
    "resources": {
      "cpu_limit": 2,
      "cpu_reservation": 2,
      "mem_limit": "2G",
      "mem_reservation": "2G",
      "generic_resources": {}
    },
    "placement": {
      "constraints": []
    },
    "container_spec": {
      "image": "xnat/datascience-notebook:JHP-76",
      "command": null,
      "env": {
        "XNAT_DATA": "/data",
        "XNAT_HOST": "http://localhost:8080",
        "XNAT_PASS": "xxxxx",
        "XNAT_USER": "xxxxx,
        "XNAT_ITEM_ID": "MyProject",
        "XNAT_XSI_TYPE": "xnat:projectData",
        "XDG_CONFIG_HOME": "/workspace/admin",
        "JUPYTERHUB_ROOT_DIR": "/workspace/admin"
      },
      "labels": {},
      "mounts": [
        {
          "target": "/workspace/admin",
          "source": "/data/xnat/workspaces/users/admin",
          "type": "bind",
          "read_only": false
        },
        {
          "target": "/data/projects/MyProject/experiments",
          "source": "./MyProject/arc001",
          "type": "bind",
          "read_only": true
        }
      ]
    }
  }
}
```

```
[INFO 2024-08-16 17:17:07,774 xnat-jupyterhub pre_spawn_hook:97] Mounting the following volumes for user admin server 20240816T171702861Z:
 - {'name': 'home', 'persistentVolumeClaim': {'claimName': 'workspaces'}}
 - {'name': 'archive', 'persistentVolumeClaim': {'claimName': 'archive'}}
 - {'mountPath': '/workspace/{username}', 'name': 'home', 'subPath': 'users/{username}'}
 - {'name': 'archive', 'mountPath': '/data/projects/MyProject/experiments', 'readOnly': True, 'subPath': './MyProject/arc001'}
```

**Comment by andylassiter** [comment]
@fxusyd The path translation preferences are not included in the UserOptions model but applied to the mounts before the UserOptions are built. It looks like path translation was applied to your archive path but not workspace mounts.

Looking at the logic, path translation is only applied if both the server and docker path translations preferences are non-blank. Maybe that should be changed to only if one is non-blank?

https://github.com/NrgXnat/xnat-jupyterhub-plugin/blob/ac56884a0f8d685166cead68389112810f2a90a0/src/main/java/org/nrg/xnatx/plugins/jupyterhub/services/impl/DefaultUserOptionsService.java#L440

https://github.com/NrgXnat/xnat-jupyterhub-plugin/blob/ac56884a0f8d685166cead68389112810f2a90a0/src/main/java/org/nrg/xnatx/plugins/jupyterhub/services/impl/DefaultUserOptionsService.java#L457

**Comment by fxusyd** [comment]
@andylassiter I tested with Path Translation Docker Archive Prefix set to . , it works! Like what you suggested, update the setting label/description to be less Docker specific would be good, . can even be default when archive mounts a pvc.

**Comment by andylassiter** [comment]
Sorry for the slow reply, just returned from vacation. 

Great! I will merge my changes and also update the plugin setting label/description. We're planning a 1.3 release this month, these changes will be included.

**Pull request merged**
